### ISSUE TITLE
Improve parameter casting

### ISSUE THREAD

**Issue by whamtet** [whamtet/ctmx#2]
int -> long, float -> double, array -> vector

**Comment by ieugen** [comment]
This might be related to an issue I found, or  ifound a bug:

I started a new project using leiningen template.
I updated dependencies.

Starte the project and I saw 5xx errors. 
Logs showed: 
```clojure
java.lang.ClassCastException: class java.lang.String cannot be cast to class java.lang.Number (java.lang.String and java.lang.Number are in module java.base of loader 'bootstrap')
        at clojure.lang.Numbers.inc(Numbers.java:139)
        at jlp.routes.home$this__10541__auto____15337.invoke(home.clj:37)
        at jlp.routes.home$this__10541__auto____15337.invoke(home.clj:37)
        at jlp.routes.home$home_routes$fn__15351.invoke(home.clj:50)
        at reitit.ring$ring_handler$fn__12406.invoke(ring.cljc:329)
        at clojure.lang.AFn.applyToHelper(AFn.java:154)
        at clojure.lang.AFn.applyTo(AFn.java:144)
        at clojure.lang.AFunction$1.doInvoke(AFunction.java:31)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at clojure.lang.Var.invoke(Var.java:384)
        at ring.middleware.reload$wrap_reload$fn__5417.invoke(reload.clj:39)
        at selmer.middleware$wrap_error_page$fn__5432.invoke(middleware.clj:18)
        at prone.middleware$wrap_exceptions$fn__5674.invoke(middleware.clj:169)
        at ring.middleware.flash$wrap_flash$fn__8929.invoke(flash.clj:39)
        at ring.adapter.undertow.middleware.session$wrap_undertow_session$fn__9472.invoke(session.clj:77)
        at ring.middleware.keyword_params$wrap_keyword_params$fn__9566.invoke(keyword_params.clj:53)
        at ring.middleware.nested_params$wrap_nested_params$fn__9624.invoke(nested_params.clj:89)
        at ring.middleware.multipart_params$wrap_multipart_params$fn__9756.invoke(multipart_params.clj:171)
        at ring.middleware.params$wrap_params$fn__9783.invoke(params.clj:75)
        at ring.middleware.cookies$wrap_cookies$fn__9245.invoke(cookies.clj:214)
        at ring.middleware.absolute_redirects$wrap_absolute_redirects$fn__9971.invoke(absolute_redirects.clj:47)
        at ring.middleware.resource$wrap_resource_prefer_resources$fn__9819.invoke(resource.clj:25)
        at ring.middleware.content_type$wrap_content_type$fn__9919.invoke(content_type.clj:34)
        at ring.middleware.default_charset$wrap_default_charset$fn__9943.invoke(default_charset.clj:31)
        at ring.middleware.not_modified$wrap_not_modified$fn__9885.invoke(not_modified.clj:61)
        at ring.middleware.x_headers$wrap_x_header$fn__9506.invoke(x_headers.clj:22)
        at ring.middleware.x_headers$wrap_x_header$fn__9506.invoke(x_headers.clj:22)
        at ring.middleware.x_headers$wrap_x_header$fn__9506.invoke(x_headers.clj:22)
        at jlp.middleware$wrap_internal_error$fn__10045.invoke(middleware.clj:18)
        at ring.adapter.undertow$undertow_handler$fn$reify__14513.handleRequest(undertow.clj:40)
        at io.undertow.server.session.SessionAttachmentHandler.handleRequest(SessionAttachmentHandler.java:68)
        at io.undertow.server.Connectors.executeRootHandler(Connectors.java:387)
        at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:852)
        at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
        at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2019)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1558)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1449)
        at org.xnio.XnioWorker$WorkerThreadFactory$1$1.run(XnioWorker.java:1280)
        at java.base/java.lang.Thread.run(Thread.java:829)
```
Reproducer: https://github.com/ieugen/jlp/blob/51d8f847863fed50286ec9fbaa4941d57f59902e/jlp/src/clj/jlp/routes/home.clj#L37

```clojure
;; using ^:int num-clicks fails 
(ctmx/defcomponent ^:endpoint npe [req ^:long num-clicks]
  (tap> (str "parsed " num-clicks))
  [:div.m-3 {:hx-post "npe"
             :hx-swap "outerHTML"
             :hx-vals {:num-clicks (inc num-clicks)}}
   "You have clicked me " num-clicks " times."])
```

**Comment by whamtet** [comment]
Thanks for your interest in ctmx @ieugen, I'd like to know how the library can best suit your needs.  I used to have `^:int` but now got rid of it because Long is the default whole value type in Clojure.  I will update the documentation to reflect this change.  Do you have any suggestions for this?

**Comment by ieugen** [comment]
Thanks for the reply and taking the time to write the project.
I think it's awesome. 
I saw you have quite a few interesting projects. 

For my use case, I think htmx / ctmx is a very good solution that I am currently exploring.
If it works well, I will be interested in contributing to the project. 
Is that something you care about / wish for? 

Regarding ^:int :
I don't have strong opinions about that.
I will come back once I have more experience with ctmx. 
I guess it should be possible to also use ^:int for the situations when it is important.
Defaulting to long is ok I if that is the default in clojure, but if I would like to use int it should let me. 
It's a tool in the end, so it should not have opinions (other than the ones we bake in them :) ) .

**Comment by whamtet** [comment]
Are you freelancing?  I am currently at a large corporate.  I enjoy the team I'm in, but would love the opportunity to use Clojure or ctmx more.

**Comment by ieugen** [comment]
> Are you freelancing? I am currently at a large corporate. I enjoy the team I'm in, but would love the opportunity to use Clojure or ctmx more.

I never considerd I do freelancing. 
I have my own (small business) that I would love to grow at a point. 

If you do like Clojure, join Clojurians Slack and you will find a lot of people there and also opportunities if you ever consider you want to pursue that (probably remote ?! ) .

At least you will be able to announce your project on announcements channel and get some feedback from people using it. 
Makes for more conversations than GH issues. 

I'm trying out ctmx/htmx for a small client project but would use it for admin tooling and personal stuff as well.

**Comment by whamtet** [comment]
Oh sure, thanks for the PR and let me know if you have any other suggestions, want help etc.
