### ISSUE TITLE
Routing broken since forward to backwards slash change

### ISSUE THREAD

**Issue by Ramblurr** [whamtet/ctmx#23]
ctmx is broken since this commit: https://github.com/whamtet/ctmx/commit/dc622ed7ae0694ff9aebac8dda536a3c5b12110f

Example stacktract from the demo:

```
java.util.regex.PatternSyntaxException: Unexpected internal error near index 1
\
	at java.base/java.util.regex.Pattern.error(Pattern.java:2028)
	at java.base/java.util.regex.Pattern.compile(Pattern.java:1789)
	at java.base/java.util.regex.Pattern.<init>(Pattern.java:1430)
	at java.base/java.util.regex.Pattern.compile(Pattern.java:1069)
	at java.base/java.lang.String.split(String.java:3153)
	at java.base/java.lang.String.split(String.java:3199)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:167)
	at clojure.lang.Reflector.invokeInstanceMethod(Reflector.java:102)
	at ctmx.rt$path.invokeStatic(rt.cljc:85)
	at ctmx.rt$path.invoke(rt.cljc:78)
	at demo.routes.click_to_edit$this__10244__auto____10436.invoke(click_to_edit.clj:26)
	at demo.routes.click_to_edit$routes$fn__10444.invoke(click_to_edit.clj:44)
	at reitit.ring$ring_handler$fn__12381.invoke(ring.cljc:329)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
```

**Comment by whamtet** [comment]
fixed in https://github.com/whamtet/ctmx/commit/970f8aec1d1418aca775f88815b1a00afe28531a

Probably time to start adding unit tests.
